This is a very incomplete list of incomplete tasks for this project 
* Code hygiene
** Testing (test)
   - [X] Create tests directory and add tests besides per-election smoketests
   - [X] Move test_*.py to tests directory
   - [ ] Quicker/easier smoketests
   - [ ] Optimize tests/test_routes.py performance: Currently very slow to run. Split into fast/slow tests using pytest marks (@pytest.mark.slow) so normal test runs are quick and comprehensive tests can be run separately with `pytest -m slow`
** Build & Packaging (build)
   - [ ] Create src directory and move most code to this directory
   - [ ] Potentially add [tool.setuptools] include-package-data = true
   - [ ] whitelist conduits.py, abif_list.yml, examples.yml, static/* and templates/*
** Refactoring (refactor)
   - [ ] Move presentation logic from templates to Python
   - [ ] Replace print() statements with the standard `logging` module
   - [ ] Clean up Python imports
   - [ ] Generate IRV transfer indicators server-side, not JavaScript.
   - [ ] Unify color styling: Generate CSS classes in one place for use by all voting methods (FPTP, IRV, STAR, etc.)
   - [ ] Remove dynamic CSS generation from templates: Currently using <style> blocks in templates for candidate colors. Consider CSS custom properties, inline styles, or pre-generated classes instead.
   - [ ] Clean up data structure passed from abiflib to STAR template
   - [X] Percentages should be calculated by abiflib, not Jinja templates
* For 0.33.0
  - [X] Sanitize candidate tokens before using them in CSS class names
  - [X] Change where it links to /id/Burl2009/pairwise#condorcet to instead link to /id/Burl2009/pairwise#pairwise
  - [X] Fix colorboxes in the Copeland/Condorcet section on /id/2022-08-16_Alaska-U.S._Representative_(Special_General)
  - [X] Create /browse route for better election discovery
  - [ ] Review [[https://github.com/electorama/awt/issues][bug list on GitHub]]
  - [ ] See [[./CHANGELOG.org]]
* Post 0.33.0
  - [ ] Create /edit route for ABIF editing interface (move editing functionality from homepage)
  - [ ] Create bifhub and figure out awt interface to it [[./docs/bifhub.md]]
  - [ ] Merge tags-index.html and tag-index.html into a single template (consolidate tag index/detail)
  - Moar [[Code hygiene]] (see above)
